### ISSUE TITLE
Node link diagram still needs love

### ISSUE THREAD

**Issue by hexrcs** [DHSTTOS/implementation#69]
Refer to #68

Tried my best to integrate the link node diagram into our main app and cleaned up some stuff, BUT.

### What's not working yet

- Tooltips don't show up somehow?? @klevia could you look into this? My guess is that they actually do get rendered, but somehow ended up being covered by other DOM (UI) elements. Tried to set its z-index to the height of Burj Khalifa but didn't work :(
https://github.com/DHSTTOS/implementation/blob/429225943fdfeddb6d4a5ba5b327c0998649ba83/frontend/src/assets/Tooltip.js#L6
- Calling `myNetwork.updateData` within the `autorun` of MobX crashes everything. Can't find out the source of this evil yet. Fk. Will keep digging into this, but @pm8008 help would be appreciated. https://github.com/DHSTTOS/implementation/blob/429225943fdfeddb6d4a5ba5b327c0998649ba83/frontend/src/components/Diagram/NodeLinkBlock.js#L13

**Comment by hexrcs** [comment]
@pm8008 BTW I changed the structure of the code for `Diagram`, not they are all in `@components`.

**Comment by pm8008** [comment]
Maybe this is due to me misunderstanding javascript, but:
NodeLinkBlock.js:9
    const myNetwork = Network();
    myNetwork(this.nodeLinkGram.current, dataStore.currentNodeLinkData);

Should the second line be myNetwork.network(...)?
Or should function Network() in line 239 end with "return network;" ?
But I'm not sure about this because when I add the return I get another error in the console:

[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@21] TypeError: "l.source is undefined"

setupData                 NodeLinkBlock.js:280
setupData                  NodeLinkBlock.js:275
updateData                NodeLinkBlock.js:245
disposer                     NodeLinkBlock.js:14
reactionRunner      8   MobX
1                                 React
reactionScheduler  4   MobX
componentDidMount  NodeLinkBlock.js:13
commitLifeCycles  13  React
[...]

**Comment by hexrcs** [comment]
@pm8008 I fixed the MobX issue in #71 via a "hack".

https://github.com/DHSTTOS/implementation/blob/6d6a650962f2c27365d5cf54ab1354d459a774fb/frontend/src/components/Diagram/NodeLinkBlock.js#L42

The reason was that hidden deep inside the `update()` and whatnot, there are some "functions" that mutate the passed in parameters themselves, adding in D3 positioning info and modifying other stuff - so in our case it's the data object inside `dataStore` gets mutated and it becomes useless when it gets passed inside `myNetwork.updateData()`, which is why it all chokes when MobX runs `myNetwork.updateData()` later on...

It was a hack because I wanted to refactor/rewrite the `Network()` <sub>(yet again)</sub> to utilize cleaner modern JS syntax, while also making everything inside the drawing procedures immutable. Failed again as there's too much stuff intertwined together.

(Maybe a tip: if there's ever a need to transform some data inside an array, use `Array.map` and reassign it instead of `Array.forEach`, which mutates the array itself because everything in JS is passed by reference. The garbage collector is powerful enough so there's no need to worry about memory usage. The `x = {...x, foo: "bar"}` syntax is like a shallow copy which is pretty handy. In our case here the data object is potentially deep so I used `JSON` to make a deep clone...)
