### ISSUE TITLE
About Node-Link/Network diagram

### ISSUE THREAD

**Issue by hexrcs** [DHSTTOS/implementation#85]
My idea is to expose a server API with parameter `startTime` and `endTime`, which returns the aggregated connection status data, structured like what we already have now - `{nodes: [...], links: [...]}`. Basically we are drawing "these nodes talked via these links during 8AM to 10PM". Although within each `link` element, let's add something like `numberOfTimes: 5` or `freq: 5` to indicate that this pair of nodes talked with each other 5 times during 8AM to 10PM - this piece of information should then be displayed on the tooltip when the user hovers their cursor over one. Maybe also make the lines thicker if the `numberOfTimes` is higher.

So, the network diagram will stay static if we don't change the currently selected time span with brushing - there won't be auto "playback" feature. When the user selects another time span, the old data will be abandoned and a new `(startTime, endTime)` tuple will be used to pull data from the server again.

I am not sure how we should handle the live mode though, if we want to add dots and strokes upon every event, not batching or aggregating the events during a time interval that is. Seems like we need another set of "commands", say *upcomingEvent: `link-234` disappears along with `node-42`*, or *upcomingEvent: new `node-99` appears with `link-747` to `node-15`*.

What do you guys think? @mgonzalez01 @pm8008 @klevia

**Comment by mgonzalez01** [comment]
As for number 1, the json format then would change to:
{
 timeStamp: 223321...
nodes[]
links[ source: "", target : "", numberOfTimes : # ]
}
{
 timeStamp: 223321... + 1 second.
nodes[]
links[ source: "", target : "", numberOfTimes : # ]
}
right?

**Comment by mgonzalez01** [comment]
for realTime i'm not sure, really what we could do is create the aggreagtion every time it's requested from time started to current time, As I remember Ankush's diagram draws all nodes encountered no matter the time and then only draws the links for that second.

**Comment by hexrcs** [comment]
> As for number 1, the json format then would change to:
> {
> timeStamp: 223321...
> nodes[]
> links[ source: "", target : "", numberOfTimes : # ]
> }
> {
> timeStamp: 223321... + 1 second.
> nodes[]
> links[ source: "", target : "", numberOfTimes : # ]
> }
> right?

Not exactly, since we already aggregate the links and nodes, don't calculate the changes every second, but only by the given `startTime` and `endTime` params. This way it's more flexible.

For example, if we want an overview of network topology between 8AM to 10PM, JSON looks like:

```
{
startTimeStamp: 8AM...
endTimeStamp: 10PM...
nodes[...]
links[ source: "", target : "", numberOfTimes : # ]
}
```

And if we do want to get "animation frames" @ 1FPS, we get a bunch of JSONs back, or an array, like:

```
{
startTimeStamp: 8AM...
endTimeStamp: 8AM + 1s
nodes[...]
links[ source: "", target : "", numberOfTimes : # ]
}
...
{
startTimeStamp: 10PM -1s
endTimeStamp: 10PM
nodes[...]
links[ source: "", target : "", numberOfTimes : # ]
}
```

**Comment by mgonzalez01** [comment]
aggregation doesn't work currently for start and end times :( but I'll try and make it work.

**Comment by mgonzalez01** [comment]
Would it then be sensible to pre compute the topology for the whole set and recompute the requests on demand?

**Comment by hexrcs** [comment]
> pre compute the topology for the whole set

Could you elaborate? Like the whole timespan aggregation as we currently have?

**Comment by mgonzalez01** [comment]
yeah exactly.

**Comment by mgonzalez01** [comment]
>And if we do want to get "animation frames" @ 1FPS, we get a bunch of JSONs back, or an array, like:

For this then the client would request it in 1 s bursts, right?
because if not then it's 2 types of aggregation

**Comment by hexrcs** [comment]
> yeah exactly

Why do we need that then? We should be able to specify a period of time - if the user wants to see the whole timespan, we just request `startTime: BIRTH_OF_UNIVERSE`, `endTime: DEATH_OF_UNIVERSE`. No need to do that in advance.

> For this then the client would request it in 1 s bursts, right?

This is analog to the `+1 second` in the example you gave above. I'm not sure if we need this though, perhaps one possible way to implement realtime mode. Basically either:

> we need another set of "commands", say _upcomingEvent: `link-234` disappears along with `node-42`_, or _upcomingEvent: new `node-99` appears with `link-747` to `node-15`_.

... or

> create the aggreagtion every time it's requested from time started to current time

Or better ideas :)

**Comment by mgonzalez01** [comment]
functionally they're pretty similar but supporting both as you wrote them need 2 different types of aggregation. 

 1 aggregation for a time range:
>{
>startTimeStamp: 8AM...
>endTimeStamp: 10PM...
>nodes[...]
>links[ source: "", target : "", numberOfTimes : # ]
>}

and another one for the "animation frames"

>{
>startTimeStamp: 8AM...
>endTimeStamp: 8AM + 1s
>nodes[...]
>links[ source: "", target : "", numberOfTimes : # ]
>}
>...
>{
>startTimeStamp: 10PM -1s
>endTimeStamp: 10PM
>nodes[...]
>links[ source: "", target : "", numberOfTimes : # ]
>}

or the client does multiple requests of the first type spaced out in seconds for the number of animation frames it wants.

**Comment by hexrcs** [comment]
I think type 1 is definitely what we will put into use (start/end time params), but not sure about "animation frames" or "events".

If "frames", maybe a new type of aggregation makes sense. Maybe add another parameter for the resolution - 1FPS or 60FPS for example. We can certainly reuse the type 1 aggregation, and just make a new server API (eg. a new `cmd: REQUEST_NODE_LINK_FRAMES` with `par: {start: yesterday noon, end: today noon}`), then let the hub interpret that single request into say 14400 smaller backend queries, each of which spanning 1 second. However I imagine that way there's way too much overhead.

**Comment by mgonzalez01** [comment]
I like that. less work for me.

**Comment by mgonzalez01** [comment]
Implemeted #1 
@pm8008 care to weigh in be what Leo said before closing the issue?

**Comment by hexrcs** [comment]
Maybe leave it open until we decide what to do with the live mode?

**Comment by pm8008** [comment]
I agree with type 1.
I can add a new request+response for that, np.
I think it's possible that the hub answers to a request like {start: 8am, end: 9am, fps: 1} by executing 3600 database queries and sending 3600 messages to the client, but I'll have to check the websocket API. 

As for precomputing the topology: I think with realtime data that's not completely possible because it could happen that a node that doesn't show up in the archived data suddenly sends a packet.
I'd suggest that the client has a list of "all nodes seen up to now" where new nodes get added, and draws the node-link-diagram based on that list. I.e. the "circle of nodes" would over time get more crowded. (Unless we bother to implement some kind of expiration mechanism for inactive nodes.)

**Comment by pm8008** [comment]
I agree with type 1.
I can add a new request+response for that, np.
It's definitely possible for the hub to answer to a request like {start: 8am, end: 9am, fps: 1} by executing 3600 database queries and sending 3600 messages to the client.

As for precomputing the topology: I think with realtime data that's not completely possible because it could happen that a node that doesn't show up in the archived data suddenly sends a packet.
I'd suggest that the client has a list of "all nodes seen up to now" where new nodes get added, and draws the node-link-diagram based on that list. I.e. the "circle of nodes" would over time get more crowded. (Unless we bother to implement some kind of expiration mechanism for inactive nodes.)

**Comment by pm8008** [comment]
I agree with type 1.
I can add a new request+response for that, np.
It's definitely possible for the hub to answer to a request like {start: 8am, end: 9am, fps: 1} by executing 3600 database queries and sending 3600 messages to the client.

As for precomputing the topology: I think with realtime data that's not completely possible because it could happen that a node that doesn't show up in the archived data suddenly sends a packet.
I'd suggest that the client has a list of "all nodes seen up to now" where new nodes get added, and draws the node-link-diagram based on that list. I.e. the "circle of nodes" would over time get more crowded. (Unless we bother to implement some kind of expiration mechanism for inactive nodes.)
